plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "xuweikang"
email: 1028606271@qq.com
description: ""
github:
  username: xuweikang
swiftype:
  searchId: 
comment:
    repo: blog
    client_id: dbf77f176519397e3a05
    client_secret: 5d43499dd24b40d7772cda441e700d6c2b528291

url: "https://xuweikang.github.io"
imgrepo: "https://xuweikang.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

